server:
    port: 9700 #${random.int(9500,9600)}
spring:
  application:
    name: feign-user
eureka:
  instance:
    non-secure-port: ${server.port}
    preferIpAddress: true #像eureka服务注册信息时，使用ip地址，默认使用hostname
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #eureka的服务地址

feign:
  hystrix:
    enabled: false